name: Node.js CI/CD with SonarQube, JEST, Cypress E2E, and Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"] # Choose the appropriate Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./client/node_modules
            ./backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    needs: setup-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t bassmit123/benzine-server:latest ./server

      - name: Push Backend Docker Image to Docker Hub
        run: docker push bassmit123/benzine-server:latest:latest


